### ISSUE TITLE
Problema sleep no uworkers.core.AbstractConsumer

### ISSUE THREAD

**Issue by roneigebert** [Skullabs/uWorkers#8]
Quando um consumer é iniciado e após um tempo ocorre um problema de conexão com o activemq, no método handleJMSException o sleep sempre vai ser zero, pois waitingCounter.next() sempre retorna zero, Isso faz com que entre em um loop de processamento, travando até o sistema operacional.

**Comment by miere** [comment]
É estranho pq o _waitingCounter_ é um contador Fibonacci, não deveria ser zero nunca... Acho que o bug então deve estar Fibonacci. Deixa eu averiguar aqui.

**Comment by roneigebert** [comment]
Resolvido @miere =D

**Comment by miere** [comment]
Man, confesso q não curti a solução.
Não faz sentido corrigir no Abstract, uma vez que o problema está no Fibonacci que não era corretamente iniciado. Por favor, considere o patch feito na branch _hotfix/1_.

**Comment by roneigebert** [comment]
A alteração no Abstract não foi para o zero, apenas para nao ultrapassar o limit do Fibonacci... na classe Fibonacci também tinha efetuado o ajuste para iniciar com valor 1.

**Comment by miere** [comment]
Mas daí o problema parece ser outro. Saca só, tem um método reset lá?
Não é correto expor o current... Faz parte do escopo interno do Fibonacci. [Lei de Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter), mano! ;P
Troca, então, para um if que cheque se tem proximo, se não tiver, faz reset.

**Comment by roneigebert** [comment]
Esse IF é para ser colocado la no Abstract ou dentro do metodo next do Fibonacci (e dai tirar o IF do abstract)? E já faço na master ou quer que vá primeiro para branch que vc criou?

**Comment by miere** [comment]
@roneigebert saca só, eu só vi agora que tu havias commitado na master...
Vamos fazer o seguinite, deixa assim, já que a sua versão já funciona bacana, e vamos projetar a nova versão do uWorkers para q este problema não aconteça mais... ;)
